# Generated by Django 4.2.6 on 2024-01-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=79005622791, max_length=50),
            preserve_default=False,
        ),
    ]
