# Generated by Django 4.2.6 on 2024-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_first_name_order_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=256),
        ),
    ]
